[package]
name = "rainr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.22.1"
clap = { version = "3.0.0-rc.9", features = ["derive"] }
rand = "0.8.4"
ezemoji = "0.2.1"
palette = "0.6.0"
